public class Player {
    public void playing(){

        string player1Name = 'Ronaldo';
        system.debug(player1Name);

        string player2Name = 'Messi';
        system.debug(player2Name);

        string player3Name = 'Neymar';
        system.debug(player3Name);

        string player4Name = 'Alex';
        system.debug(player4Name);

        string player5Name = 'Hagi';
        system.debug(player5Name);

    }
}
